#!/usr/bin/env sh
# =============================================================================
#  DikaBuff — one-shot installer
#  Builds the CLI, installs the `dikabuff` command globally, and adds it to
#  your PATH — automatically, on any platform:
#
#    Android/Termux  → $PREFIX/bin (already on PATH)
#    Linux/Arch/VPS  → ~/.local/bin  (or /usr/local/bin with --system)
#    macOS           → ~/.local/bin
#    Git Bash/MSYS/Cygwin → ~/.local/bin + dikabuff.cmd shim
#    WSL             → ~/.local/bin
#
#  Usage:
#    sh install.sh            # install (fast path: skips build if already built)
#    sh install.sh --full     # force fresh npm install + build
#    sh install.sh --system   # install into /usr/local/bin (needs write access)
#    DIKABUFF_BIN=~/mydir sh install.sh   # custom bin dir
#    DIKABUFF_NO_PROFILE=1 sh install.sh  # don't touch shell rc files
#
#  Windows PowerShell users: run  .\install.ps1  instead.
# =============================================================================

set -e

# --- 0. Resolve the real project directory (works from any cwd) ------------
PROJECT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

say()  { printf '%s\n' "$*"; }
die()  { say "[dikabuff] ERROR: $*" >&2; exit 1; }
note() { say "[dikabuff] $*"; }

# --- 1. Platform detection ---------------------------------------------------
OS="$(uname -s 2>/dev/null || printf unknown)"

PLATFORM=unknown
if [ -n "${PREFIX:-}" ] && [ -d "$PREFIX/bin" ]; then
  PLATFORM=termux                       # Android/Termux
elif [ "${OS#MINGW}" != "$OS" ] || [ "${OS#MSYS}" != "$OS" ] || [ "${OS#CYGWIN}" != "$OS" ]; then
  PLATFORM=windows-bash                 # Git Bash / MSYS2 / Cygwin
elif [ "${OS#Darwin}" != "$OS" ]; then
  PLATFORM=macos
elif [ "${OS#Linux}" != "$OS" ]; then
  PLATFORM=linux                        # Arch, Debian, Fedora, VPS, WSL…
fi

# --- 2. Choose the global bin directory --------------------------------------
if [ -n "${DIKABUFF_SYSTEM:-}" ] || [ "$1" = "--system" ]; then
  BIN_DIR=/usr/local/bin
elif [ -n "${DIKABUFF_BIN:-}" ]; then
  BIN_DIR=$DIKABUFF_BIN
elif [ "$PLATFORM" = "termux" ]; then
  BIN_DIR=$PREFIX/bin
else
  BIN_DIR=$HOME/.local/bin
  if [ ! -w "$HOME" ]; then
    BIN_DIR=$HOME/bin
  fi
fi

if [ "$PLATFORM" = "unknown" ]; then
  say "[dikabuff] Unrecognized platform ($OS) — using ~/.local/bin."
  PLATFORM=linux
fi

# --- 3. Prerequisites ---------------------------------------------------------
if ! command -v node >/dev/null 2>&1; then
  die "Node.js is required but not found. Install it first:
       Termux:  pkg install nodejs
       Debian/Ubuntu:  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - && sudo apt install -y nodejs
       Arch:    sudo pacman -S nodejs npm"
fi
if ! command -v npm >/dev/null 2>&1 && [ ! -f "$PROJECT_DIR/package.json" ]; then
  die "npm is required but not found."
fi

# --- 4. Install deps + build --------------------------------------------------
cd "$PROJECT_DIR"

node_modules_exist() { [ -d "$PROJECT_DIR/node_modules" ]; }
binary_exists()      { [ -f "$PROJECT_DIR/apps/dikabuff-cli/dist/index.js" ]; }

FULL=0
for a in "$@"; do [ "$a" = "--full" ] && FULL=1; done

if ! node_modules_exist || [ "$FULL" = "1" ]; then
  note "installing dependencies (npm install)…"
  npm install --no-audit --no-fund
  # npm ≥10.2 approving build scripts (esbuild). Safe no-op elsewhere.
  npm install-scripts approve esbuild >/dev/null 2>&1 || true
  npm rebuild esbuild >/dev/null 2>&1 || true
else
  note "node_modules present — skipping npm install (use --full to force)."
fi

if ! binary_exists || [ "$FULL" = "1" ]; then
  note "building the CLI (npm run build)…"
  npm run build >/dev/null
else
  note "CLI already built — skipping build (use --full to force)."
fi

# --- 5. Install the `dikabuff` command ----------------------------------------
mkdir -p "$BIN_DIR" || die "cannot create bin dir: $BIN_DIR"

# Termux has no /usr/bin/env — resolve a direct sh path for the launcher shebang.
if [ "$PLATFORM" = "termux" ]; then
  SH_PATH="$(command -v sh 2>/dev/null || printf '/bin/sh')"
  WRAPPER_SHEBANG="#!$SH_PATH"
else
  WRAPPER_SHEBANG="#!/usr/bin/env sh"
fi

INSTALLED=
if [ "$PLATFORM" = "windows-bash" ]; then
  # POSIX wrapper (Git Bash / MSYS / Cygwin / WSL)
  cat > "$BIN_DIR/dikabuff" <<WRAPPER
$WRAPPER_SHEBANG
# DikaBuff launcher (generated by install.sh — safe to delete & reinstall)
exec node "$PROJECT_DIR/apps/dikabuff-cli/dist/index.js" "\$@"
WRAPPER
  chmod +x "$BIN_DIR/dikabuff"
  INSTALLED="dikabuff"

  # Windows cmd/PowerShell shim
  if command -v cygpath >/dev/null 2>&1; then
    WIN_PROJECT=$(cygpath -w "$PROJECT_DIR" 2>/dev/null || printf '%s' "$PROJECT_DIR")
    cat > "$BIN_DIR/dikabuff.cmd" <<CMDEOF
@echo off
node "$WIN_PROJECT\\apps\\dikabuff-cli\\dist\\index.js" %*
CMDEOF
    INSTALLED="dikabuff + dikabuff.cmd"
  fi
else
  cat > "$BIN_DIR/dikabuff" <<WRAPPER
$WRAPPER_SHEBANG
# DikaBuff launcher (generated by install.sh — safe to delete & reinstall)
exec node "$PROJECT_DIR/apps/dikabuff-cli/dist/index.js" "\$@"
WRAPPER
  chmod +x "$BIN_DIR/dikabuff"
  INSTALLED="dikabuff"
fi

note "installed $INSTALLED → $BIN_DIR"

# --- 6. Add the bin dir to PATH (idempotent) ----------------------------------
already_on_path() {
  case ":$PATH:" in
    *":$BIN_DIR:"*) return 0 ;;
    *) return 1 ;;
  esac
}

if [ -n "${DIKABUFF_NO_PROFILE:-}" ]; then
  note "PATH profile update skipped (DIKABUFF_NO_PROFILE=1)."
elif already_on_path; then
  note "$BIN_DIR is already on PATH."
else
  PROFILE_UPDATED=0
  PATH_LINE="export PATH=\"$BIN_DIR:\$PATH\"  # dikabuff"

  # fish
  FISH_CONFIG="$HOME/.config/fish/config.fish"
  if command -v fish >/dev/null 2>&1 || [ -f "$FISH_CONFIG" ]; then
    mkdir -p "$(dirname "$FISH_CONFIG")"
    if ! grep -qs "dikabuff" "$FISH_CONFIG" 2>/dev/null; then
      printf '\n# >>> dikabuff >>>\nset -gx PATH "%s" $PATH\n# <<< dikabuff <<<\n' "$BIN_DIR" >> "$FISH_CONFIG"
      PROFILE_UPDATED=1
    fi
  fi

  # zsh
  if [ -n "$ZSH_VERSION" ] || [ -f "$HOME/.zshrc" ]; then
    if ! grep -qs "dikabuff" "$HOME/.zshrc" 2>/dev/null; then
      printf '\n# >>> dikabuff >>>\n%s\n# <<< dikabuff <<<\n' "$PATH_LINE" >> "$HOME/.zshrc"
      PROFILE_UPDATED=1
    fi
  fi

  # bash (only if zsh wasn't the active shell — avoids double-wiring on zsh+oh-my-zsh)
  if [ -z "${ZSH_VERSION:-}" ] && { [ -n "$BASH_VERSION" ] || [ -f "$HOME/.bashrc" ]; }; then
    if ! grep -qs "dikabuff" "$HOME/.bashrc" 2>/dev/null; then
      printf '\n# >>> dikabuff >>>\n%s\n# <<< dikabuff <<<\n' "$PATH_LINE" >> "$HOME/.bashrc"
      PROFILE_UPDATED=1
    fi
  fi

  # fallback: ~/.profile (sh/dash, login shells)
  if [ "$PROFILE_UPDATED" = "0" ] && [ -f "$HOME/.profile" ] || [ "$PROFILE_UPDATED" = "0" ]; then
    if ! grep -qs "dikabuff" "$HOME/.profile" 2>/dev/null; then
      printf '\n# >>> dikabuff >>>\n%s\n# <<< dikabuff <<<\n' "$PATH_LINE" >> "$HOME/.profile"
      PROFILE_UPDATED=1
    fi
  fi

  # Windows user PATH (for usage from cmd / PowerShell via the .cmd shim)
  if [ "$PLATFORM" = "windows-bash" ] && command -v powershell.exe >/dev/null 2>&1; then
    WIN_BIN=$(cygpath -w "$BIN_DIR" 2>/dev/null || true)
    if [ -n "$WIN_BIN" ]; then
      powershell.exe -NoProfile -Command \
        "\$p=[Environment]::GetEnvironmentVariable('Path','User'); if(\$p -notlike '*$WIN_BIN*'){[Environment]::SetEnvironmentVariable('Path',\$p+';$WIN_BIN','User')}" \
        >/dev/null 2>&1 && note "Windows user PATH updated ($WIN_BIN)." || true
    fi
  fi

  [ "$PROFILE_UPDATED" = "1" ] && note "PATH updated — open a new terminal, or run:  export PATH=\"$BIN_DIR:\$PATH\""
  [ "$PROFILE_UPDATED" = "0" ] && note "could not auto-update a profile — add this to your shell rc:  export PATH=\"$BIN_DIR:\$PATH\""
fi

# --- 7. Make it work in the CURRENT session + verify ---------------------------
export PATH="$BIN_DIR:$PATH"
cd "$OLDPWD" 2>/dev/null || true

if command -v dikabuff >/dev/null 2>&1; then
  VERSION=$(dikabuff --version 2>/dev/null || true)
  say ""
  say "✔ dikabuff is ready  (v${VERSION:-?})"
  say "  try:  dikabuff --help        or just  dikabuff  to start chatting"
else
  die "installed, but \`dikabuff\` is not resolvable — check PATH contains: $BIN_DIR"
fi